agents:
  queue: clima
  slurm_mem: 12G
  modules: climacommon/2024_10_09

env:
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    concurrency: 1
    concurrency_group: 'depot/climaland-ci'
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.add(\"MPI\"); Pkg.add(\"CUDA\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate lib/ClimaLandSimulations"
      - "julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_gpus: 1
      # Ensures that we have all the 8 tasks on the same node
      slurm_nodes: 1
      slurm_ntasks_per_node: 8
      slurm_queue: "invalid"
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

