name: ClimaLandSimulations CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  lib-climalandsimulations:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version:
            - '1.10'
            - '1.11'
#  julia-actions/cache@v2 did not seem to invalidate cache correctly...
#    - uses: julia-actions/cache@v2
      - name: Install Julia dependencies
        run: >
          julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.develop(path=".")'
      - name: Run the tests
        continue-on-error: true
        env:
            CI_OUTPUT_DIR: output
        run: >
          julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.test("ClimaLandSimulations")'
